import type { CookieJar } from "tough-cookie";
import type { OrderRisk } from "../types.js";
import {
  ORIGIN,
  SUBMIT_ORDER_PATH,
  allowedCheckoutContextRequest,
} from "./policy.js";
import { FetchDOM, pause } from "./dom.mjs";

const PREFIX = "x-dq7hy5l1-";
const CORE_FIELDS = ["a", "b", "c", "d", "f", "z"];
export function needsRequestProtection(path: string): boolean {
  return (
    path === "/apiproxy/v1/orchestra/price-order" || path === SUBMIT_ORDER_PATH
  );
}
export interface SessionContextOptions {
  cookieJar: CookieJar;
  fetch: typeof globalThis.fetch;
  timeoutMs: number;
}
export interface SessionContext {
  headers(path: string, body: string): Promise<Headers>;
  risk(): Promise<OrderRisk>;
  close(): void;
}

/** An ephemeral context generated by current website scripts, using only the auth cookie jar. */
export class LiveSessionContext implements SessionContext {
  private readonly dom: FetchDOM;
  private window: any;
  private bootstrapToken?: string;
  private failure?: Error;
  private closed = false;
  private registrationComplete = false;
  private preparing?: { path: string; body: string; headers?: Headers };
  private queue: Promise<unknown> = Promise.resolve();
  private readonly userAgent =
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36";

  constructor(private readonly options: SessionContextOptions) {
    this.dom = new FetchDOM({
      jar: options.cookieJar,
      userAgent: this.userAgent,
      request: this.contextRequest.bind(this),
    });
  }

  private async contextRequest(input: URL, init: any = {}): Promise<Response> {
    const url = new URL(String(input)),
      method = (init.method ?? "GET").toUpperCase();
    if (this.closed) throw new Error("Session context is closed");
    if (this.failure) throw this.failure;
    // Observe the vendor's fetch hook locally. It can never send an application request.
    if (url.origin === ORIGIN && needsRequestProtection(url.pathname)) {
      if (
        method !== "POST" ||
        url.search ||
        this.preparing?.path !== url.pathname ||
        this.preparing.body !== init.body
      )
        throw new Error(
          "Unexpected application request during context preparation",
        );
      this.preparing.headers = new Headers(init.headers);
      return Response.json({});
    }
    if (!allowedCheckoutContextRequest(url, method))
      throw new Error("Session context destination blocked");
    const headers = new Headers(init.headers);
    headers.set("user-agent", this.userAgent);
    headers.set("accept-language", "en-US,en;q=0.9");
    if (init.referer) headers.set("referer", init.referer);
    if (init.origin && method === "POST") headers.set("origin", init.origin);
    const cookie = await this.options.cookieJar.getCookieString(url.href);
    if (cookie) headers.set("cookie", cookie);
    else headers.delete("cookie");
    const response = await this.options.fetch(url, {
      method,
      headers,
      body: init.body,
      redirect: "error",
      signal: AbortSignal.timeout(this.options.timeoutMs),
    });
    for (const cookie of response.headers.getSetCookie())
      await this.options.cookieJar.setCookie(cookie, url.href);
    if (!response.ok) {
      this.failure = new Error(
        `Session context returned HTTP ${response.status}; request not sent`,
      );
      throw this.failure;
    }
    if (
      url.origin === ORIGIN &&
      url.pathname === "/vendor/static/vendor2.js" &&
      !url.search
    ) {
      this.bootstrapToken = (await response.clone().text()).match(
        /init\("([^"]+)"/,
      )?.[1];
    }
    if (
      url.origin === "https://prod.accdab.net" &&
      url.pathname === "/beacon/gt"
    )
      this.registrationComplete = true;
    return response;
  }

  private async open(): Promise<void> {
    if (this.window) return;
    await this.contextRequest(new URL(ORIGIN + "/"));
    this.window = this.dom.open(
      '<!doctype html><html lang="en-US"><head><script src="/vendor/static/vendor2.js"></script><script src="https://prod.accdab.net/cdn/cs/F3YqEeKYX8DMWEu7kxZT1ymCLP4.js"></script><script src="/weblx/assets/iovation-first-third.js"></script></head><body></body></html>',
      ORIGIN + "/menu/cart",
      (window: any) => {
        window.Headers = Headers;
        window.Request = Request;
        window.Response = Response;
        window.IGLOO = {
          loader: { uri_hook: "/iojs", version: "general5" },
          bb_callback(value: string, complete: boolean) {
            window.io_value = value;
            window.io_complete = complete;
          },
        };
      },
    );
    await this.dom.settle(100);
    if (this.failure) throw this.failure;
    if (!this.bootstrapToken)
      throw new Error("Fresh vendor bootstrap unavailable; request not sent");
  }

  private serialized<T>(run: () => Promise<T>): Promise<T> {
    const result = this.queue.then(async () => {
      if (this.closed) throw new Error("Session context is closed");
      let timer: ReturnType<typeof setTimeout> | undefined;
      try {
        return await Promise.race([
          (async () => {
            await this.open();
            return run();
          })(),
          new Promise<never>((_, reject) => {
            timer = setTimeout(() => {
              this.failure = new Error(
                "Fresh session context timed out; request not sent",
              );
              this.close();
              reject(this.failure);
            }, this.options.timeoutMs);
          }),
        ]);
      } finally {
        clearTimeout(timer);
      }
    });
    this.queue = result.catch(() => {});
    return result;
  }

  private valid(headers: Headers): boolean {
    return (
      CORE_FIELDS.every((suffix) => !!headers.get(PREFIX + suffix)) &&
      headers.get(PREFIX + "f") === this.bootstrapToken
    );
  }

  headers(path: string, body: string): Promise<Headers> {
    if (!needsRequestProtection(path))
      return Promise.reject(new Error("Unsupported protected operation"));
    return this.serialized(async () => {
      this.preparing = { path, body };
      try {
        await this.window.fetch(path, {
          method: "POST",
          credentials: "same-origin",
          body,
          headers: { "content-type": "application/json" },
        });
        let headers = this.preparing.headers ?? new Headers();
        if (!this.valid(headers)) {
          // The same vendor form hook used by the fetch login can produce the core proof.
          // FetchDOM records form submission locally; no form is sent to Starbucks.
          const form = this.window.document.createElement("form");
          form.method = "POST";
          form.action = path;
          this.window.document.body.appendChild(form);
          const start = this.dom.submissions.length;
          try {
            form.submit();
            const deadline = Date.now() + this.options.timeoutMs;
            while (
              this.dom.submissions.length === start &&
              Date.now() < deadline
            )
              await pause(25);
            const submission = this.dom.submissions[start];
            if (!submission || submission.url !== ORIGIN + path)
              throw new Error(
                "Fresh vendor proof did not complete; request not sent",
              );
            headers = new Headers();
            for (const [key, value] of submission.fields)
              if (key.toLowerCase().startsWith(PREFIX)) headers.set(key, value);
          } finally {
            form.remove();
          }
        }
        if (this.failure) throw this.failure;
        if (!this.valid(headers))
          throw new Error("Fresh vendor proof is incomplete; request not sent");
        const result = new Headers();
        for (const suffix of [...CORE_FIELDS, "a0"]) {
          const value = headers.get(PREFIX + suffix);
          if (value) result.set(PREFIX + suffix, value);
        }
        return result;
      } finally {
        this.preparing = undefined;
      }
    });
  }

  risk(): Promise<OrderRisk> {
    return this.serialized(async () => {
      const deadline = Date.now() + this.options.timeoutMs;
      while (
        (!this.window.io_complete ||
          !this.window._bcn?.getToken() ||
          !this.registrationComplete) &&
        Date.now() < deadline
      ) {
        if (this.failure) throw this.failure;
        await pause(25);
      }
      const deviceFingerprint = this.window.io_value,
        ubaId = this.window._bcn?.getToken();
      if (
        !this.window.io_complete ||
        !deviceFingerprint ||
        !ubaId ||
        !this.registrationComplete
      )
        throw new Error("Fresh device risk did not complete");
      this.window._bcn.flush();
      await this.dom.settle(25);
      if (this.failure) throw this.failure;
      return {
        platform: "Web",
        market: "US",
        ccAgentName: "WebApp",
        deviceFingerprint,
        reputation: { deviceFingerprint, ubaId },
      };
    });
  }

  close(): void {
    this.closed = true;
    this.dom.close();
  }
}
